import React, { useMemo, useState } from 'react';
import { categories, levels, allTechniques } from './data/wrestling';
import { trainingStages, progressionRules, progressSteps, homeSessions, equipment, readiness, weeklyPlan } from './data/training';
import './styles.css';

const navItems = [...categories.map(c => c.id), 'тренировки', 'прогресс'];
const youtube = q => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + ' wrestling tutorial')}`;
const imageSearch = q => `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(q + ' wrestling technique')}`;

function load(key){ try { return JSON.parse(localStorage.getItem(key) || '[]'); } catch { return []; } }

function App(){
  const [page,setPage] = useState('главная');
  const [filters,setFilters] = useState({group:'Все',level:'Все'});
  const [query,setQuery] = useState('');
  const [selected,setSelected] = useState(null);
  const [theme,setTheme] = useState(() => localStorage.getItem('wrestling-theme') || 'night');
  const [favorites,setFavorites] = useState(() => load('wrestling-favorites'));
  const [completed,setCompleted] = useState(() => load('wrestling-completed'));
  const [techCompleted,setTechCompleted] = useState(() => load('wrestling-tech-completed'));
  const [equipmentDone,setEquipmentDone] = useState(() => load('wrestling-equipment'));
  const [readinessDone,setReadinessDone] = useState(() => load('wrestling-readiness'));
  const [menuOpen,setMenuOpen] = useState(false);

  const toggle = (key,setter,storage) => setter(prev => { const next = prev.includes(key) ? prev.filter(x=>x!==key) : [...prev,key]; localStorage.setItem(storage,JSON.stringify(next)); return next; });
  const active = categories.find(c=>c.id===page);

  const items = useMemo(() => {
    if(!active) return [];
    return active.groups.flatMap(g=>g.items.map(([name,level,english,text,lesson])=>({name,level,english,text,lesson,group:g.title,jp:g.jp,video:youtube(english),image:imageSearch(english),media:{video:youtube(english),image:imageSearch(english),status:'external-search'}})))
      .filter(x => (filters.group==='Все' || x.group===filters.group) && (filters.level==='Все' || x.level===filters.level))
      .filter(x => !query || `${x.name} ${x.english} ${x.group}`.toLowerCase().includes(query.toLowerCase()));
  },[active,filters,query]);

  const go = next => { setPage(next); setQuery(''); setFilters({group:'Все',level:'Все'}); setMenuOpen(false); window.scrollTo({top:0,behavior:'smooth'}); };
  const changeTheme = () => { const next = theme==='night'?'day':'night'; setTheme(next); localStorage.setItem('wrestling-theme',next); };

  return <div className={`site ${theme}`}>
    <header className="header">
      <button className="logo" onClick={()=>go('главная')}><span>闘</span><b>WRESTLING</b><small>БОРЬБА · ТЕХНИКА · ТРЕНИРОВКИ</small></button>
      <nav>{navItems.map(item=><button key={item} className={page===item?'active':''} onClick={()=>go(item)}>{item==='тренировки'?'Тренировки':item==='прогресс'?'Прогресс':categories.find(c=>c.id===item)?.title}</button>)}</nav>
      <div className="headerTools"><button className="themeToggle" onClick={changeTheme} aria-label="Сменить тему">{theme==='night'?'☼':'☾'}</button><div className="favorites">★ {favorites.length}</div><button className="menuButton" onClick={()=>setMenuOpen(v=>!v)} aria-label="Открыть меню">{menuOpen?'×':'☰'}</button></div>
    </header>
    {menuOpen && <div className="mobileMenu">{navItems.map(item=><button key={item} className={page===item?'active':''} onClick={()=>go(item)}>{item==='тренировки'?'Тренировки':item==='прогресс'?'Прогресс':categories.find(c=>c.id===item)?.title}</button>)}</div>}

    {page==='главная' ? <Home go={go} theme={theme}/> : page==='тренировки' ? <Training completed={completed} toggleCompleted={key=>toggle(key,setCompleted,'wrestling-completed')} equipmentDone={equipmentDone} toggleEquipment={key=>toggle(key,setEquipmentDone,'wrestling-equipment')} readinessDone={readinessDone} toggleReadiness={key=>toggle(key,setReadinessDone,'wrestling-readiness')} /> : page==='прогресс' ? <Progress completed={completed} techCompleted={techCompleted} total={allTechniques.length} equipmentDone={equipmentDone} readinessDone={readinessDone} /> : <Catalog active={active} filters={filters} setFilters={setFilters} query={query} setQuery={setQuery} items={items} favorites={favorites} toggleFavorite={key=>toggle(key,setFavorites,'wrestling-favorites')} setSelected={setSelected} />}
    {selected && <Modal item={selected} favorite={favorites.includes(selected.name)} techniqueDone={techCompleted.includes(selected.name)} toggleTechnique={()=>toggle(selected.name,setTechCompleted,'wrestling-tech-completed')} toggleFavorite={()=>toggle(selected.name,setFavorites,'wrestling-favorites')} onClose={()=>setSelected(null)} />}
    <footer><span>WRESTLING</span><span>Техника • дисциплина • уважение</span><span>Тренируйся последовательно и безопасно.</span></footer>
  </div>
}

function Home({go,theme}){ return <main>
  <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,7,13,.97) 0%,rgba(4,7,13,.84) 42%,rgba(4,7,13,.25) 75%,rgba(4,7,13,.35) 100%),url('/wrestling-japan.png')`}}>
    <div className="hero-copy"><span className="eyebrow">WRESTLING / БОРЬБА</span><h1>Техника.<br/><em>Контроль.</em><br/>Движение.</h1><p>Общая база для борцовских дисциплин: универсальная стойка, проходы, броски, работа ногами, партер, ОФП и домашняя подготовка.</p><div className="actions"><button className="primary" onClick={()=>go('стойка')}>Открыть стойку →</button><button className="ghost" onClick={()=>go('тренировки')}>Домашняя тренировка</button></div></div>
    <div className="hero-mark"><span>闘</span><b>WRESTLING</b><small>{theme==='night'?'夜':'昼'} · БОРЬБА</small></div>
  </section>
  <section className="sectionIntro"><div><span className="eyebrow">03 РАЗДЕЛА</span><h2>Всё начинается с движения.</h2></div><p>Три основных направления без лишнего: стойка, партер и ОФП. Внутри — большая библиотека техники, уровни сложности и практические тренировки.</p></section>
  <section className="grid">{categories.map((c,i)=><button className="category" key={c.id} onClick={()=>go(c.id)}><small>0{i+1} · {c.jp}</small><h2>{c.title}</h2><p>{c.description}</p><strong>{c.groups.reduce((n,g)=>n+g.items.length,0)} приёмов и элементов</strong><b>↗</b></button>)}</section>
  <section className="principles"><div><span className="eyebrow">ОСНОВА</span><h2>Универсальная стойка — общий старт.</h2><p>Нейтральная разножка, короткие шаги, баланс и изменение уровня подходят как фундамент для разных борцовских правил.</p></div><div className="list"><p><b>01</b> Стопы и баланс.</p><p><b>02</b> Перемещение без скрещивания.</p><p><b>03</b> Изменение уровня ногами.</p><p><b>04</b> Сначала позиция — потом атака.</p></div></section>
  <section className="themePanel"><div><span className="eyebrow">ДВЕ ТЕМЫ</span><h2>Днём — рисовая бумага. Ночью — чернила и неон.</h2><p>Переключатель в шапке сохраняет выбранную тему.</p></div><div className="themePreview"><span>☼</span><span>☾</span></div></section>
</main> }

function Catalog({active,filters,setFilters,query,setQuery,items,favorites,toggleFavorite,setSelected}){ return <main><section className="pageHero"><div><span className="eyebrow">WRESTLING / {active.jp}</span><h1>{active.title}</h1><p>{active.description}</p></div><div className="stamp">闘<br/><small>{active.title}</small></div></section><section className="toolbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск техники, приёма, раздела…" /></div><div className="tabs"><button className={filters.group==='Все'?'active':''} onClick={()=>setFilters({...filters,group:'Все'})}>Все</button>{active.groups.map(g=><button key={g.id} className={filters.group===g.title?'active':''} onClick={()=>setFilters({...filters,group:g.title})}>{g.title}</button>)}</div><div className="levels">{levels.map(l=><button key={l} className={filters.level===l?'active':''} onClick={()=>setFilters({...filters,level:l})}>{l}</button>)}</div></section><div className="catalogHead"><div><span className="eyebrow">Каталог</span><h2>{items.length} элементов</h2></div><span className="catalogNote">Лёгкий · Средний · Продвинутый</span></div><section className="cards">{items.map((item,i)=><article className="card" key={item.name}><div className="visual"><span>{String(i+1).padStart(2,'0')}</span><b>{item.jp}</b><strong>闘</strong><em className={item.level}>{item.level}</em></div><div className="body"><small>{item.group} · {item.english}</small><h3>{item.name}</h3><p>{item.text}</p><div className="cardActions"><button onClick={()=>setSelected(item)}>Разбор →</button><a href={item.video} target="_blank" rel="noreferrer">▶ Видео</a><a href={item.image} target="_blank" rel="noreferrer">▧ Фото</a><button className={favorites.includes(item.name)?'fav on':'fav'} onClick={()=>toggleFavorite(item.name)}>{favorites.includes(item.name)?'★':'☆'}</button></div></div></article>)}</section></main> }

function Modal({item,favorite,techniqueDone,toggleTechnique,toggleFavorite,onClose}){ return <div className="overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="modalArt"><span>{item.jp}</span><strong>闘</strong><em>{item.level}</em></div><div className="modalBody"><span className="eyebrow">{item.group} · {item.english}</span><h2>{item.name}</h2><p className="lead">{item.text}</p><section className="lesson"><h4>Обучение</h4><p>{item.lesson}</p><ol><li>Сначала положение и движение без сопротивления.</li><li>Затем медленные качественные повторы.</li><li>После стабильной техники — лёгкое сопротивление.</li><li>Опасные броски, удушающие и болевые осваивай только с тренером и подготовленным партнёром.</li></ol></section><div className="warning">Безопасность: любой сигнал партнёра — немедленная остановка. Боль, головокружение или потеря контроля — повод прекратить упражнение.</div><div className="modalActions"><a className="primary" href={item.video} target="_blank" rel="noreferrer">Смотреть обучение →</a><a className="ghost" href={item.image} target="_blank" rel="noreferrer">Открыть фото →</a><button className="ghost" onClick={toggleTechnique}>{techniqueDone?'✓ Изучено':'○ Отметить изученным'}</button><button className="ghost" onClick={toggleFavorite}>{favorite?'★ В избранном':'☆ В избранное'}</button></div></div></div></div> }
function Training({completed,toggleCompleted,equipmentDone,toggleEquipment,readinessDone,toggleReadiness}){ return <main><section className="pageHero"><div><span className="eyebrow">WRESTLING / ДОМА</span><h1>Тренировки</h1><p>Домашняя подготовка построена вокруг трёх этапов: база, связки и раунды. Каждый этап можно проходить в своём темпе.</p></div><div className="stamp">家<br/><small>ДОМ</small></div></section><section className="trainingGrid">{trainingStages.map(stage=><article className="trainingCard" key={stage.id}><span>0{stage.id}</span><h2>{stage.title}</h2><b>{stage.duration}</b><p>{stage.goal}</p><div className="stageEquipment"><small>Нужно для этапа</small><div>{stage.equipment.map(item=><span key={item}>{item}</span>)}</div></div><ul>{stage.blocks.map((block,i)=><li key={i}><button className={completed.includes(stage.id+':'+i)?'check done':'check'} onClick={()=>toggleCompleted(stage.id+':'+i)}>✓</button>{block}</li>)}</ul></article>)}</section><section className="homeSection"><div><span className="eyebrow">ГОТОВЫЕ ФОРМАТЫ</span><h2>Выбери тренировку под день</h2><p>Короткая — для занятых дней, стандартная — для регулярной работы, кондиционная — для подготовленного спортсмена.</p></div><div className="sessionGrid">{homeSessions.map(session=><article className="sessionCard" key={session.id}><small>Этап {session.stage}</small><h3>{session.title}</h3><b>{session.duration}</b><p>{session.description}</p><ul>{session.blocks.map((block,i)=><li key={i}>{block}</li>)}</ul></article>)}</div></section><section className="homeSection"><div><span className="eyebrow">ПЕРЕД ТРЕНИРОВКОЙ</span><h2>Проверь готовность</h2><p>Если хотя бы один базовый пункт не выполнен, сократи нагрузку или перенеси тренировку.</p></div><div className="checkGrid">{readiness.map((item,i)=><button key={i} className={readinessDone.includes(String(i))?'checkItem done':'checkItem'} onClick={()=>toggleReadiness(String(i))}><span>{readinessDone.includes(String(i))?'✓':'○'}</span>{item}</button>)}</div></section><section className="homeSection"><div><span className="eyebrow">ЭКИПИРОВКА</span><h2>Что необходимо дома</h2><p>Минимум — безопасное покрытие, пространство, резина и вода. Остальное расширяет варианты тренировок.</p></div><div className="equipmentGrid">{equipment.map(item=><article className={equipmentDone.includes(item.id)?'equipment done':'equipment'} key={item.id}><div><strong>{item.name}</strong><small>{item.required?'Необходимо':'По возможности'}</small></div><p>{item.detail}</p><button onClick={()=>toggleEquipment(item.id)}>{equipmentDone.includes(item.id)?'✓ Проверено':'Отметить'}</button></article>)}</div></section><section className="weekly"><span className="eyebrow">НЕДЕЛЯ</span><h2>Простой недельный ритм</h2><div className="weekGrid">{weeklyPlan.map(day=><article key={day.day}><b>{day.day}</b><h3>{day.title}</h3><p>{day.focus}</p></article>)}</div></section></main> }
function Progress({completed,techCompleted,total,equipmentDone,readinessDone}){ const workoutTotal=trainingStages.reduce((n,s)=>n+s.blocks.length,0); const workoutPct=Math.min(100,Math.round(completed.length/Math.max(workoutTotal,1)*100)); const techPct=Math.min(100,Math.round(techCompleted.length/Math.max(total,1)*100)); const readinessPct=Math.round(readinessDone.length/readiness.length*100); const equipmentPct=Math.round(equipmentDone.length/equipment.length*100); return <main><section className="pageHero"><div><span className="eyebrow">WRESTLING / ПРОГРЕСС</span><h1>Прогресс</h1><p>Следи не только за количеством тренировок, но и за изученной техникой, готовностью и регулярностью.</p></div><div className="progressRing"><strong>{workoutPct}%</strong><small>домашний цикл</small></div></section><section className="progressStats"><article><strong>{workoutPct}%</strong><span>тренировки</span></article><article><strong>{techPct}%</strong><span>техника</span></article><article><strong>{readinessPct}%</strong><span>готовность</span></article><article><strong>{equipmentPct}%</strong><span>оборудование</span></article></section><section className="progressBox"><h2>Домашний цикл</h2><div className="bar"><span style={{width:`${workoutPct}%`}}></span></div><p>{completed.length} из {workoutTotal} пунктов отмечено</p></section><section className="progressBox"><h2>Изучение техники</h2><div className="bar"><span style={{width:`${techPct}%`}}></span></div><p>{techCompleted.length} из {total} элементов отмечено как изученные</p></section><section className="progressSteps">{progressSteps.map((step,i)=><article key={step.title}><span>0{i+1}</span><div><h2>{step.title}</h2><p>{step.text}</p></div></article>)}</section><section className="progressRules"><h2>Как повышать нагрузку</h2><div className="ruleGrid">{progressionRules.map(rule=><article key={rule.title}><h3>{rule.title}</h3><p>{rule.text}</p></article>)}</div></section></main> }
export default App;
