services:
  - type: web
    name: wrestling
    runtime: docker
    plan: free
    region: frankfurt
    repo: https://github.com/avernus666/wrestling-
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/ready
    autoDeploy: yes
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wrestling-db
          property: connectionString
      - key: CORS_ORIGINS
        sync: false
      - key: SESSION_TTL
        value: 720h
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DB_MAX_CONNS
        value: "20"
      - key: DB_MIN_CONNS
        value: "2"

databases:
  - name: wrestling-db
    plan: free
    region: frankfurt
    databaseName: wrestling
    user: wrestling
